### ISSUE TITLE
Crab component - error als lijst adressen leeg is

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/vue_component_library#16]
![image](https://github.com/OnroerendErfgoed/vue_component_library/assets/1849458/c29c40b2-e48c-4d09-95ee-e209a7785afb)

reproduceerbaar met 
![image](https://github.com/OnroerendErfgoed/vue_component_library/assets/1849458/ffd36543-c0d2-4b09-9fc4-2c6ecff25b25)

**Comment by wouter-adriaens** [comment]
Vertrekkende vanuit een lege form niet te reproduceren.

Reproduceren door eerst ander adres in te geven dat huisnummers heeft, dan straat wijzigen naar Beekweg. (dewelke geen huisnummers heeft).
Lijst met huisnummers wordt niet correct gereset waardoor selectie mogelijk is en error voorkomt.
