### ISSUE TITLE
InputPhone component - landcode wordt niet geupdatet na wijzigen

### ISSUE THREAD

**Issue by pegahmoh** [OnroerendErfgoed/vue_component_library#212]
Landcode wijzigingen wordt niet bewaard. Het lukt enkel als nummer is ook gewijzigd.
Te testen in beheer - aanvrager tab van energieadvies en erkenning metaaldetectie.

**Comment by AxelVerstappen** [comment]
Was gewoon een probleem door foute conditionals in metaaldetectie / energieadvies, component in vcl werkt zoals verwacht https://github.com/OnroerendErfgoed/vue_component_library/issues/212
