### ISSUE TITLE
Aanpassingen aan adrescomponent

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/vue_component_library#63]
![image](https://github.com/OnroerendErfgoed/vue_component_library/assets/1850704/bc8d5977-62f4-49be-a43c-f11bdffde95a)

**Comment by claeyswo** [comment]
Voor mij was niet direct duidelijk wat er met 'Huisnummer niet gevonden?' en 'Suggesties' bedoeld werd.
Misschien kan wat extra tekst het verbeteren? of kan de tekst enkel getoond worden als een huisnummer ingegeven werd dat niet in de suggestielijst staat?

voorstel voor uitgebreidere tekst:

Een postcode invullen die niet tussen de suggesties staat?
Terug naar suggesties

Een straat invullen die niet tussen de suggesties staat?
Terug naar suggesties

Een huisnummer invullen dat niet tussen de suggesties staat?
Terug naar suggesties

Een busnummer invullen dat niet tussen de suggesties staat?
Terug naar suggesties

**Comment by cedrikv** [comment]
lijst van chatgtp:
Antwerpen - NIS-code: 10000
Limburg - NIS-code: 7000
Oost-Vlaanderen - NIS-code: 4000
Vlaams-Brabant - NIS-code: 2000
West-Vlaanderen - NIS-code: 3000

**Comment by cedrikv** [comment]
Deze direct meenemen? https://github.com/OnroerendErfgoed/vue_component_library/issues/33
